apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/regal-scholar-423322-h0/backend-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: PGHOST
          value: "34.72.51.3"
        - name: PGDATABASE
          value: "postgres"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "Ashu123"
